webpack.config.js: Replace isStaging helper function with temp variable
SyntaxError: Unexpected identifier coming from import ENVIRONMENTS from 'site/constants/environments';
I suspect it's because we're using node@10, which doesn't support import statements.