Switches to useNavigate()
Test suite returns the following error:
Error: Uncaught [Error: useNavigate() may be used only in the context of a <Router> component.]