add medallia styling as separate output (#14312)
* add medallia styling as separate output

* fix reference to va-medallia-style

* update filenaming logic for css to exclude medallia styles from filename hashing

* package.json: Add build:webpack:prod npm script

* webpack.config.js: Temporarily disable sourcemaps

* package.json: Add debug:webpack:prod npm script

* webpack.config.js: Use 'contenthash' substitution instead of interpolated 'entryModule.renderedHash'

* Revert "webpack.config.js: Temporarily disable sourcemaps"

This reverts commit 646a5e67b81055704a99b6eb5c06d5ba227a4e46.

* webpack.config.js: Remove hash from Medallia style filename in staging

* package.json: Add build:webpack:staging, build:webpack:dev, and build:webpack:local npm scripts

* webpack.config.js: Update Medallia spelling (from medalia to medallia)

* Update config/webpack.config.js

Co-authored-by: Rian Fowler <rian.fowler@adhocteam.us>

* webpack.config.js: Replace temp 'isStaging' variable with 'isStaging' environment helper

* Update config/webpack.config.js

Co-authored-by: Eugene Doan <1067024+U-DON@users.noreply.github.com>

* webpack.config.js: Replace isStaging helper function with temp variable

SyntaxError: Unexpected identifier coming from import ENVIRONMENTS from 'site/constants/environments';
I suspect it's because we're using node@10, which doesn't support import statements.

* webpack.config.js: Use webpack substitutions instead of ES6 string interpolations

* webpack.config.js: Delete leftover closing curly brace

Co-authored-by: Bill Fienberg <billfienberg@gmail.com>
Co-authored-by: Bill Fienberg <billfienberg@users.noreply.github.com>
Co-authored-by: Eugene Doan <1067024+U-DON@users.noreply.github.com>